# LongName is the expanded name of the site
LongName: Kent State University
# Description is a brief description of your site
Description: Kent State Research

# If you have an up-to-date local git clone, fill ID with the output from `bin/next_site_id`
# Otherwise, leave it blank and we will fill in the appropriate value for you.
ID: <ID>

# AddressLine1 is the street address of the site
AddressLine1: 800 Hilltop Dr, Kent, OH 44240
### AddressLine2 (optional) is the second line of the street address
# AddressLine2: Room 101
# City is the city the site is located in
City: Kent 

# Country is the country the site is located in
Country: United States
### State (optional) is the state or province the site is located in
State: Ohio
### Zipcode (optional) is the zipcode/postal code of the site
Zipcode: "44240"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 41.1498
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -81.3433
